packages:
  - packages/*

catalog:
  '@arethetypeswrong/cli': ^0.18.2
  '@oxlint/plugins': 1.64.0
  '@types/node': ^24.12.4
  '@typescript/native-preview': 7.0.0-dev.20260515.1
  c8: ^11.0.0
  oxfmt: ^0.49.0
  oxlint: ^1.63.0
  publint: ^0.3.21
  rimraf: ^6.1.3
  typescript: 6.0.3
  vitest: ^4.1.5
