import { defineConfig } from 'oxlint';

type PluginDevOxlintConfigOptions = {
  whitespaceSpecifier: string;
};

export const definePluginDevOxlintConfig = ({ whitespaceSpecifier }: PluginDevOxlintConfigOptions) =>
  defineConfig({
    categories: {
      correctness: 'off',
    },
    env: {
      builtin: true,
      node: true,
    },
    ignorePatterns: ['coverage/**', 'dist/**', 'node_modules/**'],
    jsPlugins: [
      {
        name: '@mkaradeniz/whitespace',
        specifier: whitespaceSpecifier,
      },
    ],
    overrides: [
      {
        files: ['**/*.cjs', '**/*.js', '**/*.mjs'],
        env: {
          es2026: true,
          node: true,
        },
      },
      {
        files: ['**/*.ts', '**/*.tsx'],
        env: {
          es2026: true,
          node: true,
        },
        plugins: ['typescript'],
        rules: {
          'constructor-super': ['off'],
          'getter-return': ['off'],
          'no-array-constructor': ['warn'],
          'no-const-assign': ['off'],
          'no-dupe-class-members': ['off'],
          'no-dupe-keys': ['off'],
          'no-empty-function': ['warn', { allow: [] }],
          'no-func-assign': ['off'],
          'no-import-assign': ['off'],
          'no-new-native-nonconstructor': ['off'],
          'no-obj-calls': ['off'],
          'no-redeclare': ['off'],
          'no-setter-return': ['off'],
          'no-this-before-super': ['off'],
          'no-unreachable': ['off'],
          'no-unsafe-negation': ['off'],
          'no-unused-expressions': ['warn'],
          'no-unused-vars': [
            'warn',
            {
              argsIgnorePattern: '^_',
              destructuredArrayIgnorePattern: '^_',
            },
          ],
          'no-useless-constructor': ['warn'],
          'typescript/adjacent-overload-signatures': ['warn'],
          'typescript/array-type': ['warn', { default: 'generic' }],
          'typescript/ban-ts-comment': ['warn', { minimumDescriptionLength: 10 }],
          'typescript/ban-tslint-comment': ['warn'],
          'typescript/class-literal-property-style': ['warn'],
          'typescript/consistent-generic-constructors': ['warn'],
          'typescript/consistent-indexed-object-style': ['warn'],
          'typescript/consistent-type-assertions': ['warn'],
          'typescript/consistent-type-definitions': ['warn', 'type'],
          'typescript/consistent-type-imports': [
            'warn',
            {
              fixStyle: 'inline-type-imports',
              prefer: 'type-imports',
            },
          ],
          'typescript/no-confusing-non-null-assertion': ['warn'],
          'typescript/no-duplicate-enum-values': ['warn'],
          'typescript/no-dynamic-delete': ['warn'],
          'typescript/no-empty-object-type': ['warn'],
          'typescript/no-explicit-any': ['warn'],
          'typescript/no-extra-non-null-assertion': ['warn'],
          'typescript/no-extraneous-class': ['warn'],
          'typescript/no-inferrable-types': ['warn'],
          'typescript/no-invalid-void-type': ['warn'],
          'typescript/no-misused-new': ['warn'],
          'typescript/no-namespace': ['warn'],
          'typescript/no-non-null-asserted-nullish-coalescing': ['warn'],
          'typescript/no-non-null-asserted-optional-chain': ['warn'],
          'typescript/no-non-null-assertion': ['warn'],
          'typescript/no-require-imports': ['warn'],
          'typescript/no-this-alias': ['warn'],
          'typescript/no-unnecessary-type-constraint': ['warn'],
          'typescript/no-unsafe-declaration-merging': ['warn'],
          'typescript/no-unsafe-function-type': ['warn'],
          'typescript/no-wrapper-object-types': ['warn'],
          'typescript/prefer-as-const': ['warn'],
          'typescript/prefer-for-of': ['warn'],
          'typescript/prefer-function-type': ['warn'],
          'typescript/prefer-literal-enum-member': ['warn'],
          'typescript/prefer-namespace-keyword': ['warn'],
          'typescript/triple-slash-reference': ['warn'],
          'typescript/unified-signatures': ['warn'],
        },
      },
    ],
    plugins: ['import', 'unicorn'],
    rules: {
      '@mkaradeniz/whitespace/jsx-child-spacing': ['warn'],
      '@mkaradeniz/whitespace/react-next-organization': ['warn'],
      '@mkaradeniz/whitespace/statement-spacing': ['warn'],
      'array-callback-return': ['warn', { allowImplicit: true, allowVoid: false, checkForEach: false }],
      'block-scoped-var': ['warn'],
      curly: ['warn', 'all'],
      'default-case-last': ['warn'],
      eqeqeq: ['warn'],
      'for-direction': ['warn'],
      'func-names': ['warn', 'as-needed'],
      'grouped-accessor-pairs': ['warn'],
      'import/first': ['warn'],
      'import/no-absolute-path': ['warn'],
      'import/no-cycle': ['warn'],
      'import/no-duplicates': ['warn'],
      'import/no-mutable-exports': ['warn'],
      'import/no-self-import': ['warn'],
      'new-cap': ['warn', { capIsNew: false, newIsCap: true, properties: true }],
      'no-alert': ['warn'],
      'no-async-promise-executor': ['warn'],
      'no-bitwise': ['warn'],
      'no-caller': ['warn'],
      'no-case-declarations': ['warn'],
      'no-class-assign': ['warn'],
      'no-compare-neg-zero': ['warn'],
      'no-cond-assign': ['warn'],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      'no-constant-binary-expression': ['warn'],
      'no-constant-condition': ['warn'],
      'no-constructor-return': ['warn'],
      'no-control-regex': ['warn'],
      'no-debugger': ['warn'],
      'no-delete-var': ['warn'],
      'no-dupe-else-if': ['warn'],
      'no-duplicate-case': ['warn'],
      'no-else-return': ['warn'],
      'no-empty': ['warn'],
      'no-empty-character-class': ['warn'],
      'no-empty-pattern': ['warn'],
      'no-eval': ['warn'],
      'no-ex-assign': ['warn'],
      'no-extend-native': ['warn'],
      'no-extra-bind': ['warn'],
      'no-extra-boolean-cast': ['warn', { enforceForLogicalOperands: true }],
      'no-extra-label': ['warn'],
      'no-global-assign': ['warn'],
      'no-implicit-coercion': ['warn', { boolean: true, disallowTemplateShorthand: false, number: true, string: true }],
      'no-inner-declarations': ['warn'],
      'no-invalid-regexp': ['warn'],
      'no-irregular-whitespace': ['warn'],
      'no-iterator': ['warn'],
      'no-label-var': ['warn'],
      'no-labels': ['warn'],
      'no-lone-blocks': ['warn'],
      'no-lonely-if': ['warn'],
      'no-misleading-character-class': ['warn'],
      'no-multi-assign': ['warn'],
      'no-nested-ternary': ['warn'],
      'no-new': ['warn'],
      'no-new-func': ['warn'],
      'no-new-wrappers': ['warn'],
      'no-nonoctal-decimal-escape': ['warn'],
      'no-param-reassign': ['warn'],
      'no-promise-executor-return': ['warn'],
      'no-proto': ['warn'],
      'no-prototype-builtins': ['warn'],
      'no-regex-spaces': ['warn'],
      'no-return-assign': ['warn'],
      'no-script-url': ['warn'],
      'no-self-assign': ['warn'],
      'no-self-compare': ['warn'],
      'no-sequences': ['warn'],
      'no-shadow-restricted-names': ['warn'],
      'no-sparse-arrays': ['warn'],
      'no-template-curly-in-string': ['warn'],
      'no-unneeded-ternary': ['warn'],
      'no-unsafe-finally': ['warn'],
      'no-unsafe-optional-chaining': ['warn'],
      'no-unused-labels': ['warn'],
      'no-unused-private-class-members': ['warn'],
      'no-useless-backreference': ['warn'],
      'no-useless-call': ['warn'],
      'no-useless-catch': ['warn'],
      'no-useless-computed-key': ['warn'],
      'no-useless-concat': ['warn'],
      'no-useless-escape': ['warn'],
      'no-useless-rename': ['warn'],
      'no-useless-return': ['warn'],
      'no-var': ['warn'],
      'no-with': ['warn'],
      'object-shorthand': ['warn'],
      'prefer-const': ['warn'],
      'prefer-numeric-literals': ['warn'],
      'prefer-object-spread': ['warn'],
      'prefer-rest-params': ['warn'],
      'prefer-spread': ['warn'],
      'prefer-template': ['warn'],
      'require-yield': ['warn'],
      'symbol-description': ['warn'],
      'unicorn/number-literal-case': ['off'],
      'unicorn/prefer-node-protocol': ['warn'],
      'use-isnan': ['warn'],
      'valid-typeof': ['warn'],
    },
  });
